### ISSUE TITLE
L3 system flow diagram refactoring

### ISSUE THREAD

**Issue by Yenyun035** [CSE112-sp22-group9/cse112-sp22-group9#10]
## Name and Email
  - Name: Yen-Yun Wu
  - Email: yew005@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 1
  
## Issue Description
  - L3 system flow diagram refactoring

**Comment by Rick10101221** [comment]
New Automated Jira Ticket Key: NL-39

[Ticket Link](https://nine-lives.atlassian.net/jira/software/projects/NL/boards/1/backlog?selectedIssue=NL-39)
