### ISSUE TITLE
Move X button on settings to the corner

### ISSUE THREAD

**Issue by JMRam30** [CSE112-sp22-group9/cse112-sp22-group9#106]
## Name and Email
  - Name: Justin Ramirez
  - Email: jmr002@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 1
  
## Issue Description
  - Visual bug, X button is currently located just under the user profile image in settings, should be moved to corner.

**Comment by DustinLin** [comment]
Closed with PR #115
