### ISSUE TITLE
Save button visual improvements

### ISSUE THREAD

**Issue by DustinLin** [CSE112-sp22-group9/cse112-sp22-group9#113]
## Name and Email
  - Name: Dustin
  - Email: d6lin@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 2
  
## Issue Description
  - The current "save" button above notes is not responsive to the user. We need some sort of signal to the user when the data is saved. Some ideas could be disabling the button and replacing the text with "Saved!", and enabling the button when the notes are changed again.

**Comment by sophiaklu** [comment]
maybe an alert at the top that it was saved? like the alerts on the login page

**Comment by Yenyun035** [comment]
currently we use alert() for all alerts in Weekly Preview page.
if we want to use a custom alert, we'll need to change all those alert() to make them consistent.

**Comment by cfellowes** [comment]
Used a custom alert in #144
