### ISSUE TITLE
DailyOverview Theme Setup

### ISSUE THREAD

**Issue by Rick10101221** [CSE112-sp22-group9/cse112-sp22-group9#125]
## Name and Email
  - Name: Rickesh Khilnani
  - Email: rickeshkhilnani@gmail.com

## Complexity of Issue (Scale from 1-5)
  - 
  
## Issue Description
  - Grabbing user theme from backend and adding it to frontend for DailyOverview.html

**Comment by DustinLin** [comment]
Closed with PR #126
