### ISSUE TITLE
 NL-41 Changing documentation for YearlyOverview/YearlyJS

### ISSUE THREAD

**Issue by cfellowes** [CSE112-sp22-group9/cse112-sp22-group9#13]
## Name and Email
  - Name: Christopher Fellowes
  - Email: cfellowe@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 1
  
## Issue Description
  - Updating comments and style for YearlyJS.js

**Comment by Rick10101221** [comment]
New Automated Jira Ticket Key: NL-41

[Ticket Link](https://nine-lives.atlassian.net/jira/software/projects/NL/boards/1/backlog?selectedIssue=NL-41)
