### ISSUE TITLE
Eyeball does not work in Login/Signup Pages

### ISSUE THREAD

**Issue by Rick10101221** [CSE112-sp22-group9/cse112-sp22-group9#133]
## Name and Email
  - Name: Rickesh Khilnani
  - Email: rickeshkhilnani@gmail.com

## Complexity of Issue (Scale from 1-5)
  - 1
  
## Issue Description
  - Clicking the eyeball on the Login/Signup page does not show/hide the password field
  - Probably just an event listener error or something

**Comment by DustinLin** [comment]
Closed with Pr #137
