### ISSUE TITLE
DailyJS: Hitting back on photo album does not correctly render photo

### ISSUE THREAD

**Issue by Rick10101221** [CSE112-sp22-group9/cse112-sp22-group9#134]
## Name and Email
  - Name: Rickesh Khilnani
  - Email: rickeshkhilnani@gmail.com

## Complexity of Issue (Scale from 1-5)
  - 3
  
## Issue Description
  - Cannot perfectly traverse through photos in Photo Album
  - Hitting back does not circle around from the first photo to the last

**Comment by DustinLin** [comment]
Closed with Pr #138
