### ISSUE TITLE
NL-42 Changing documention for source/Index

### ISSUE THREAD

**Issue by JMRam30** [CSE112-sp22-group9/cse112-sp22-group9#14]
## Name and Email
  - Name: Justin Ramirez
  - Email: jmr002@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 1
  
## Issue Description
  - Updating comments/style, minor cleanup for files in source/Index/

**Comment by Rick10101221** [comment]
New Automated Jira Ticket Key: NL-42

[Ticket Link](https://nine-lives.atlassian.net/jira/software/projects/NL/boards/1/backlog?selectedIssue=NL-42)

**Comment by DustinLin** [comment]
closed with PR #18
