### ISSUE TITLE
Backend Schema

### ISSUE THREAD

**Issue by Yenyun035** [CSE112-sp22-group9/cse112-sp22-group9#15]
## Name and Email
  - Name: Yen-Yun Wu
  - Email: yew005@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 1
  
## Issue Description
  - Decide backend schema for Firebase based on IndexDB one
  - For more specific, see our firebase realtime database

**Comment by Rick10101221** [comment]
New Automated Jira Ticket Key: NL-43

[Ticket Link](https://nine-lives.atlassian.net/jira/software/projects/NL/boards/1/backlog?selectedIssue=NL-43)

**Comment by Yenyun035** [comment]
Done. Please see our firebase console -- Realtime DB.
