### ISSUE TITLE
Documentation Change forsource/MonthlyOverview

### ISSUE THREAD

**Issue by nvanny** [CSE112-sp22-group9/cse112-sp22-group9#19]
## Name and Email
  - Name: Nicholas Vanny
  - Email: nvanny@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 1
  
## Issue Description
  - Changed comments and documentation for files in MonthlyOverview

**Comment by Rick10101221** [comment]
New Automated Jira Ticket Key: NL-45

[Ticket Link](https://nine-lives.atlassian.net/jira/software/projects/NL/boards/1/backlog?selectedIssue=NL-45)
