### ISSUE TITLE
NL-14 Checking deployment sites

### ISSUE THREAD

**Issue by DustinLin** [CSE112-sp22-group9/cse112-sp22-group9#2]
Two deployments to check up one
1. Get a separate github pages site to deploy for this forked repo
2. Get a seperate github pages site to deploy the JS docs documentation (seems like just make a new repo)

Want to update the pipeline to push to these 2 new sites

**Comment by DustinLin** [comment]
This covers NL-14 on Jira

**Comment by Rick10101221** [comment]
New Automated Jira Ticket Key: NL-31

**Comment by DustinLin** [comment]
Also doing some exploratory coding involving Husky trying to implement pre-commit checks. Idea is to run local linting on staged files and check things such as branch names and commit messages before commit
