### ISSUE TITLE
Frontend Home Page

### ISSUE THREAD

**Issue by sophiaklu** [CSE112-sp22-group9/cse112-sp22-group9#23]
## Name and Email
  - Name: Chris and Sophia
  - Email: srkluete@ucsd.edu cfellowe@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 4
  
## Issue Description
  - change the frontend design of the homepage
  - add settings pop up
  - add photo album

**Comment by Rick10101221** [comment]
Associated Branch:

NL-23_frontend-update-Chris-Sophia

https://github.com/CSE112-sp22-group9/cse112-sp22-group9/tree/NL-23_frontend-update-Chris-Sophia
