### ISSUE TITLE
Refactoring Duplicate Functions

### ISSUE THREAD

**Issue by JMRam30** [CSE112-sp22-group9/cse112-sp22-group9#27]
## Name and Email
  - Name: Justin Ramirez
  - Email: jmr002@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 2
  
## Issue Description
  - There are functions in several .js files that do the same thing and may even have the same name.
  - This issue involves refactoring them and (most likely) creating a utility file for them to refer to instead.

**Comment by DustinLin** [comment]
no longer working on
