### ISSUE TITLE
frontend login/sign up page

### ISSUE THREAD

**Issue by sophiaklu** [CSE112-sp22-group9/cse112-sp22-group9#28]
## Name and Email
  - Name: Sophia and Chris
  - Email: srkluete@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 3
  
## Issue Description
  - change the frontend to look like wireframe for login/signup
  - fix toggle for changing to sign up

**Comment by Yenyun035** [comment]
Complete login frontend / backend connection. Require code clean on CSS though.

**Comment by Yenyun035** [comment]
I modified some Login.html since `<div>` overlay above input making input.onclick insensitive

**Comment by DustinLin** [comment]
closed with PR #36
