### ISSUE TITLE
Refactor Index.js

### ISSUE THREAD

**Issue by Yenyun035** [CSE112-sp22-group9/cse112-sp22-group9#29]
## Name and Email
  - Name: Yen-Yun Wu
  - Email: yew005@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 4
  
## Issue Description
  - Refactor Index.js from IndexDB version to Firebase version

- [ ] Week preview
- [ ] Monthly goals
- [ ] Yearly goals
- [ ] photo
- [ ] notes

**Comment by DustinLin** [comment]
no longer working on
