### ISSUE TITLE
Update Login/Sign Up Frontend

### ISSUE THREAD

**Issue by sophiaklu** [CSE112-sp22-group9/cse112-sp22-group9#38]
## Name and Email
  - Name: Sophia
  - Email: srkluete@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 3
  
## Issue Description
  - add in google sign in
  - add password retype and authentication, password visibility
  - make image less of screen

**Comment by DustinLin** [comment]
Closed with PR #63
