### ISSUE TITLE
Homepage Backend

### ISSUE THREAD

**Issue by Rick10101221** [CSE112-sp22-group9/cse112-sp22-group9#39]
## Name and Email
  - Name: Yen-Yun Wu and Rickesh Khilnani
  - Email: [yew005@ucsd.edu](mailto:yew005@ucsd.edu) and [rikhilna@ucsd.edu](mailto:rikhilna@ucsd.edu)

## Complexity of Issue (Scale from 1-5)
  - 4
  
## Issue Description
  - Create the backend CRUD functionality for the Homepage

**Comment by DustinLin** [comment]
Closed with PR #53
