### ISSUE TITLE
create a config folder

### ISSUE THREAD

**Issue by DustinLin** [CSE112-sp22-group9/cse112-sp22-group9#41]
## Name and Email
  - Name: Dustin Lin
  - Email: d6lin@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 1?
  
## Issue Description
  - It would be nice to refactor all our config files to a folder instead of having the around the root directory
  - do some research in how that's done
  - low priority

**Comment by Rick10101221** [comment]
Other team looked into this issue (creating folder for dot files) and they said it was too hard

So we're not doing it
