### ISSUE TITLE
Frontend calendar page

### ISSUE THREAD

**Issue by cfellowes** [CSE112-sp22-group9/cse112-sp22-group9#45]
## Name and Email
  - Name: Chris Fellowes
  - Email: cfellowe@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 4
  
## Issue Description
  - Make calendar page link to daily views when dates are clicked on. Add editable monthly/yearly goal section.

**Comment by DustinLin** [comment]
going with goals section on the bottom of cal, not on the right hand side

**Comment by DustinLin** [comment]
closed with PR #96
