### ISSUE TITLE
CRUD functions for Goals

### ISSUE THREAD

**Issue by DustinLin** [CSE112-sp22-group9/cse112-sp22-group9#46]
## Name and Email
  - Name: Dustin
  - Email: d6lin@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 3
  
## Issue Description
  - update the existing CRUD functions in the backendinit file to use firebase, try to have the same behavior

**Comment by Rick10101221** [comment]
Associated Branch: NL-39_homepage_backend-Alice_Rickesh

https://github.com/CSE112-sp22-group9/cse112-sp22-group9/tree/NL-39_homepage_backend-Alice_Rickesh

**Comment by DustinLin** [comment]
Closed with PR #53
