### ISSUE TITLE
Connect Weekly Preview Panel to Backend

### ISSUE THREAD

**Issue by Rick10101221** [CSE112-sp22-group9/cse112-sp22-group9#64]
## Name and Email
  - Name: Rickesh Khilnani
  - Email: rikhilna@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 3
  
## Issue Description
  - Going to edit WeeklyJS.js

**Comment by Rick10101221** [comment]
<img src="https://user-images.githubusercontent.com/40902144/170564471-7b484697-00f8-4407-b52b-b7ceb0fc863a.png" width="400">

**Comment by DustinLin** [comment]
Closed with PR #68
