### ISSUE TITLE
Connect Notes Panel to Backend

### ISSUE THREAD

**Issue by Rick10101221** [CSE112-sp22-group9/cse112-sp22-group9#65]
## Name and Email
  - Name: Rickesh Khilnani
  - Email: rickeshkhilnani@gmail.com

## Complexity of Issue (Scale from 1-5)
  - 3
  
## Issue Description
  - Going to edit WeeklyJS.js

### Make sure to label this issue with the 'issue' label!
<img src="https://user-images.githubusercontent.com/40902144/170565565-89d9072e-c63a-475c-befb-5b0e91ee4c1d.png" width="200">

**Comment by DustinLin** [comment]
Closed with PR #69
