### ISSUE TITLE
Connect Goal Reminders Panel to Backend

### ISSUE THREAD

**Issue by Rick10101221** [CSE112-sp22-group9/cse112-sp22-group9#66]
## Name and Email
  - Name: Rickesh Khilnani
  - Email: rickeshkhilnani@gmail.com

## Complexity of Issue (Scale from 1-5)
  - 3
  
## Issue Description
  - Going to edit WeeklyJS.js

### Make sure to label this issue with the 'issue' label!
<img src="https://user-images.githubusercontent.com/40902144/170565975-ab478b71-756a-4a9d-ba47-0d1c2fdcc4db.png" width="200">

**Comment by DustinLin** [comment]
Closed with PR #72
