### ISSUE TITLE
Connect Photo Panel with Backend

### ISSUE THREAD

**Issue by Rick10101221** [CSE112-sp22-group9/cse112-sp22-group9#67]
## Name and Email
  - Name: Rickesh Khilnani
  - Email: rickeshkhilnani@gmail.com

## Complexity of Issue (Scale from 1-5)
  - 3
  
## Issue Description
  - Going to edit WeeklyJS.js

### Make sure to label this issue with the 'issue' label!
<img src="https://user-images.githubusercontent.com/40902144/170566521-e654e5b6-5057-4882-a3ae-ea82916712cd.png" width="200">

**Comment by DustinLin** [comment]
Closed with PR #73
