### ISSUE TITLE
Implement signout from the weekly/index page

### ISSUE THREAD

**Issue by DustinLin** [CSE112-sp22-group9/cse112-sp22-group9#82]
## Issue Description
  - users should be able to signout
  - still need to decide where such a button will be, perhaps in the upper right with all the other icons? Or something that happens when you click your profile icon

**Comment by Yenyun035** [comment]
Currently the only sign out button is under user settings popup. (NL-59 branch)
Will not link PR #95 to this for now.

**Comment by Rick10101221** [comment]
Merged with #101
