### ISSUE TITLE
Exploratory Testing for IndexDB to Firebase 

### ISSUE THREAD

**Issue by Rick10101221** [CSE112-sp22-group9/cse112-sp22-group9#9]
## Name and Email
  - Name: Rickesh Khilnani
  - Email: rickeshkhilnani@gmail.com

## Complexity of Issue (Scale from 1-5)
  - 2
  
## Issue Description
  - Going to see if I can mimic the data from IndexDB (day/month/year) to Firebase Realtime DB
  - Will need more people to work on this with me (assign yourself at will)

**Comment by Rick10101221** [comment]
New Automated Jira Ticket Key: NL-37

[Ticket Link](https://nine-lives.atlassian.net/jira/software/projects/NL/boards/1/backlog?selectedIssue=NL-37)

**Comment by DustinLin** [comment]
closed with PR #20
