### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by DustinLin** [CSE112-sp22-group9/cse112-sp22-group9#92]
## Issue Description
  - come up with unit tests for the backend CRUD functions

**Comment by Rick10101221** [comment]
Dustin is still planning on looking into how to build unit tests

**Comment by DustinLin** [comment]
it doesn’t seem like there is a simple way for me to run the CRUD functions we made independently by themselves. I’ve looked into using firebase admin SDK, but that doesn’t seem appropriate because that allows us to interact with the DB itself, whereas we just want to interact with the CRUD functions (which interacts with the DB for us).
There is also using firebase emulators which seem like it may work, but that requires people to install/configure the emulator just to run the tests (and I don’t even know if this is possible as a github action). Of course these CURD function can be called when we do e2e tests so in a sense they will be tested that way.

testing has been lackluster so we won't be working on these, if there is anytime just add more to e2e tests
