### ISSUE TITLE
Incorporate dino logo into all pages and add dino favicon

### ISSUE THREAD

**Issue by sophiaklu** [CSE112-sp22-group9/cse112-sp22-group9#93]
## Name and Email
  - Name: Sophia
  - Email: srkluete@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 1
  
## Issue Description
  - add dino logo to home page and monthly
  - add dino favicon to all pages

**Comment by DustinLin** [comment]
Closed with PR #97
