### ISSUE TITLE
Add save button to notes

### ISSUE THREAD

**Issue by sophiaklu** [CSE112-sp22-group9/cse112-sp22-group9#94]
## Name and Email
  - Name: Sophia
  - Email: srkluete@ucsd.edu

## Complexity of Issue (Scale from 1-5)
  - 1
  
## Issue Description
  - add save button at bottom of notes box for users to know how to save their text box

**Comment by Rick10101221** [comment]
Completed. Will merge with upcoming PR

**Comment by DustinLin** [comment]
Closed with PR #98
